SLB_REST/Controllers/DiscogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SLB_REST.Context;
using SLB_REST.Helpers;
using SLB_REST.Helpers.DataBaseStrategy;
using SLB_REST.Helpers.Proxy;
using SLB_REST.Models;
using Newtonsoft.Json.Linq;
using SLB_REST.Helpers.ChangeDatabaseStrategy;

namespace SLB_REST.Controllers
{
    [Authorize]
    public class DiscogsController : Controller
    {
        private readonly EFContext _context;
        private readonly ProxyDiscogs _proxyDiscogs;
        private readonly ChangeDatabaseStrategy _databaseStrategy;

        public DiscogsController(
            EFContext context,
            ProxyDiscogs proxyDiscogs,
            ChangeDatabaseStrategy databaseStrategy)
        {
            _context = context;
            _proxyDiscogs = proxyDiscogs;
            _databaseStrategy = databaseStrategy;

        }

        public IActionResult Albums(string queryUser = "")
        {

            if (queryUser == "" || queryUser == null)
            {
                TempData["SearchError"] = "Wrong query, try search again";
                return View();
            }

            ViewBag.query = queryUser;

            return View();
        }

        public IActionResult GetJsonByQuery(string queryUser)
        {
            string json = _proxyDiscogs
            .Context(new JsonByUser())
            .LinkQuery(queryUser)
            .GetJson();

            return Content(json);
        }

        public IActionResult GetJsonByLink(string link)
        {
            string json = _proxyDiscogs
            .Context(new JsonByLink())
            .LinkQuery(link)
            .GetJson();

            return Content(json);
        }

        [HttpPost]
        public IActionResult Add(string link)
        {
            int userId = _context.Users
            .Where(u => u.UserName == User.Identity.Name)
            .Single().Id;

            _databaseStrategy
            .Context(new AddNewDB())
            .Data(JObject.Parse(link), userId)
            .Save(_context);

            return Ok();
        }
    }
}

SLB_REST/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="Kamil Wójcik" content="website">


    <title>SLB-Music</title>

    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/SearchAlbums.css" rel="stylesheet" />
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        @if (User.Identity.IsAuthenticated)
        {
            <a class="navbar-brand" asp-action="Albums" asp-controller="Home">
                <img id="img-logo" src="~/img/logo.png" alt="logo" width="100" height="50" />
            </a>
        }
        else
        {
            <a class="navbar-brand" asp-action="Login" asp-controller="Account">
                <img id="img-logo" src="~/img/logo.png" alt="logo" width="100" height="50" />
            </a>
        }
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="nav-link disabled" id="log-button" asp-action="LogOut" asp-controller="Account">Logout <span id="UserName">@User.Identity.Name</span><span class="sr-only">(current)</span></a>
						
                    }
                    else
                    {
                        <a class="nav-link" id="log-button" asp-action="LogIn" asp-controller="Account">Login <span class="sr-only">(current)</span></a>
                    }
                </li>
            </ul>
            @if (User.Identity.IsAuthenticated)
            {
                <form class="form-inline my-2 my-lg-0" method="get" asp-action="Albums" asp-controller="Discogs">
                    <input name="queryUser" asp-controller="Home" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            }
        </div>
    </nav>
    <script src="~/lib/jQuery/jquery-3.3.1.min.js"></script>
    <script src="~/lib/bootstrap/js/popper.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>

    @RenderBody()


</body>
</html>